config/routes.rb
Rails.application.routes.draw do
  root 'messages#new'  

  resources :messages

  post "messages/api" => "messages#create"#, defaults: { format: :xml }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery with: :exception, if: Proc.new { |c| c.request.format != 'application/json' }
  #protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json' }
  protect_from_forgery with: :null_session
end

app/controllers/messages_controller.rb
require 'json'

class MessagesController < ApplicationController
  def show
    @message = Message.find(params[:id])
  end

  def new
    
  end

  def create
    if request.content_type =~ /xml/
      message_hash = Hash.from_xml(request.body.read)

      params[:message] = {"content" => message_hash["message"]}

      @message = Message.create(message_params)
      
      url = {"url" => messages_url + "/" + @message.id.to_s}

      #url = '<?xml version = "1.0" encoding = "UTF-8" standalone ="yes"?>' + 
       #     "<url>" + 
        #      messages_url + '/' + @message.id.to_s + 
         #   "</url>"

      render :xml => url.to_xml(:root => :address, :skip_types => true)
    else
      respond_to do |format|
          format.json {
            params[:message] = {"content" => params[:message]}

            @message = Message.create(message_params)

            url = {"url" => messages_url + "/" + @message.id.to_s}

            render :json => url.to_json
          }

          format.html {
            @message = Message.create(message_params)

            render :get_url
          }
      end
    end
  end
 
  def get_url
    
  end

private
  def message_params
    params.require(:message).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Privnote</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/get_url.html.erb
<p>Message -> <b><%= request.original_url.to_s + "/" + @message.id.to_s %></b></p>
<p>The message will self-destruct after reading it.</p>

app/views/messages/new.html.erb
<%= form_with scope: :message, url: messages_path, local: true do |form| %>
  <p>
    <%= form.label :Message %><br>
    <%= form.text_area :content %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/messages/show.html.erb
<p>
  <strong>Message content</strong></br>
  <%= @message.content %>
  <% @message.destroy %>
</p>

<p>
  This message was destroyed. If you wish not to lose it, copy it before closing the window.
</p>